language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
- ./gradlew clean checkstyle build

